# Generated by Django 5.2.8 on 2025-11-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0002_alter_usuario_apellidos_alter_usuario_contraseña_and_more'),
        ('vehicles', '0002_alter_vehiculo_color_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad_litros',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad de litros'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('error', 'Error')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_servicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de servicio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_servicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de servicio'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='users.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='capacidad_max',
            field=models.IntegerField(verbose_name='Capacidad máxima'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
    ]
