# Generated by Django 5.2.8 on 2025-12-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_pedido_cantidad_litros_alter_pedido_estado_and_more'),
        ('vehicles', '0002_alter_vehiculo_color_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ubicacion',
            field=models.CharField(max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='capacidad_max',
            field=models.IntegerField(verbose_name='Capacidad máxima'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora_inicio', 'hora_fin'), name='unique_turno'),
        ),
    ]
