# Generated by Django 5.2.8 on 2025-11-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_pago', models.CharField(choices=[('aprobado', 'Aprobado'), ('pendiente', 'Pendiente'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='orders.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='payments.pago')),
            ],
        ),
    ]
