# Generated by Django 5.2.8 on 2025-11-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='fecha_procesado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesado'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reembolso', to='payments.pago', verbose_name='Pago'),
        ),
    ]
