# Generated by Django 5.2.8 on 2026-02-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_reembolso_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='reembolso',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Reembolso', 'verbose_name_plural': 'Reembolsos'},
        ),
    ]
