# Generated by Django 5.2.8 on 2025-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustible', models.CharField(choices=[('gasolina_95', 'Gasolina 95'), ('gasolina_98', 'Gasolina 98'), ('diesel', 'Diésel')], max_length=20, verbose_name='Tipo de combustible')),
                ('precio_por_litro', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio por litro')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
