# Generated by Django 5.2.8 on 2026-02-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recarga',
            options={'ordering': ['tipo_combustible'], 'verbose_name': 'Recarga', 'verbose_name_plural': 'Recargas'},
        ),
    ]
