# Generated by Django 5.2.8 on 2026-02-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehiculo_color_alter_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['marca', 'modelo', 'matricula'], 'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anyo_compra',
            field=models.IntegerField(default=0, verbose_name='Año de compra'),
        ),
    ]
