# Generated by Django 5.2.8 on 2026-02-07 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehiculo_options_vehiculo_anyo_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/', verbose_name='Imagen del vehículo')),
            ],
            options={
                'verbose_name': 'Foto del vehículo',
                'verbose_name_plural': 'Fotos de vehículos',
            },
        ),
        migrations.AddConstraint(
            model_name='vehiculo',
            constraint=models.UniqueConstraint(fields=('matricula',), name='unique_matricula'),
        ),
        migrations.AddField(
            model_name='fotovehiculo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='vehicles.vehiculo'),
        ),
    ]
