# Generated by Django 5.2.8 on 2026-02-07 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_fotovehiculo_vehiculo_unique_matricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotovehiculo',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='vehiculo',
            name='unique_matricula',
        ),
        migrations.AlterField(
            model_name='fotovehiculo',
            name='imagen',
            field=models.ImageField(upload_to='vehiculos/'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anyo_compra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL),
        ),
    ]
