# Generated by Django 5.2.8 on 2025-11-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0002_alter_pedido_cantidad_litros_alter_pedido_estado_and_more'),
        ('users', '0002_alter_usuario_apellidos_alter_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='users.usuario', verbose_name='Usuario'),
        ),
    ]
